export const FETCH_ALL_TYPES_PENDING = 'FETCH_ALL_TYPES_PENDING'
export const FETCH_ALL_TYPES_SUCCESS = 'FETCH_ALL_TYPES_SUCCESS'
export const FETCH_ALL_TYPES_FAILED = 'FETCH_ALL_TYPES_FAILED'

export const FETCH_ONE_TYPE_PENDING = 'FETCH_ONE_TYPE_PENDING'
export const FETCH_ONE_TYPE_SUCCESS = 'FETCH_ONE_TYPE_SUCCESS'
export const FETCH_ONE_TYPE_FAILED = 'FETCH_ONE_TYPE_FAILED'

export const REMOVE_TYPE_PENDING = 'REMOVE_TYPE_PENDING'
export const REMOVE_TYPE_SUCCESS = 'REMOVE_TYPE_SUCCESS'
export const REMOVE_TYPE_FAILED = 'REMOVE_TYPE_FAILED'

export const ADD_NEW_TYPE_PENDING = 'ADD_NEW_TYPE_PENDING'
export const ADD_NEW_TYPE_SUCCESS = 'ADD_NEW_TYPE_SUCCESS'
export const ADD_NEW_TYPE_FAILED = 'ADD_NEW_TYPE_FAILED'

export const EDIT_TYPE_PENDING = 'EDIT_ONE_TYPE_PENDING'
export const EDIT_TYPE_SUCCESS = 'EDIT_ONE_TYPE_SUCCESS'
export const EDIT_TYPE_FAILED = 'EDIT_ONE_TYPE_FAILED'