export const FETCH_ALL_ARCHIVE_ITEMS_PENDING = 'FETCH_ALL_ARCHIVE_ITEMS_PENDING'
export const FETCH_ALL_ARCHIVE_ITEMS_SUCCESS = 'FETCH_ALL_ARCHIVE_ITEMS_SUCCESS'
export const FETCH_ALL_ARCHIVE_ITEMS_FAILED = 'FETCH_ALL_ARCHIVE_ITEMS_FAILED'

export const FETCH_ONE_ARCHIVE_ITEM_PENDING = 'FETCH_ONE_ARCHIVE_ITEM_PENDING'
export const FETCH_ONE_ARCHIVE_ITEM_SUCCESS = 'FETCH_ONE_ARCHIVE_ITEM_SUCCESS'
export const FETCH_ONE_ARCHIVE_ITEM_FAILED = 'FETCH_ONE_ARCHIVE_ITEM_FAILED'

export const REMOVE_ARCHIVE_ITEM_PENDING = 'REMOVE_ARCHIVE_ITEM_PENDING'
export const REMOVE_ARCHIVE_ITEM_SUCCESS = 'REMOVE_ARCHIVE_ITEM_SUCCESS'
export const REMOVE_ARCHIVE_ITEM_FAILED = 'REMOVE_ARCHIVE_ITEM_FAILED'

export const ADD_NEW_ARCHIVE_ITEM_PENDING = 'ADD_NEW_ARCHIVE_ITEM_PENDING'
export const ADD_NEW_ARCHIVE_ITEM_SUCCESS = 'ADD_NEW_ARCHIVE_ITEM_SUCCESS'
export const ADD_NEW_ARCHIVE_ITEM_FAILED = 'ADD_NEW_ARCHIVE_ITEM_FAILED'

export const EDIT_ARCHIVE_ITEM_PENDING = 'EDIT_ONE_ARCHIVE_ITEM_PENDING'
export const EDIT_ARCHIVE_ITEM_SUCCESS = 'EDIT_ONE_ARCHIVE_ITEM_SUCCESS'
export const EDIT_ARCHIVE_ITEM_FAILED = 'EDIT_ONE_ARCHIVE_ITEM_FAILED'